### ISSUE TITLE
Mod has no effect in game

### ISSUE THREAD

**Issue by Chr0mia** [Exomanz/BetterStaticLights#1]
So i downloaded the mod because i used it on 1.19 and i really liked how it looked, but when using it on 1.21 it just, does nothing. Like no matter what settings i change the environment looks exactly the same.

The goal was to remove the lights on the highway in the bts environment which, from what i can tell, imblindedbythelights is unable to do, meaning that my lighting is wack atm. I've checked dependencies and made sure to download all of those. I would have checked incompatible mods but since there are no incompatible mods listed i dont know if that may be causing an issue.

The only other mod i have that changes the environments is beatsaber+ which i only use to remove the bts logo itself.

**Comment by Exomanz** [comment]
Thanks for the issue report! I'm aware of this and am looking for a fix for it--the method that I patch to make it work was removed with 1.21. I'm hoping to have a fix available soon!

**Comment by Chr0mia** [comment]
Good to know it's being worked on^^
Thanks for the quick response!

Den man. 11. apr. 2022 kl. 19.32 skrev Exomanz ***@***.***>:

**Comment by Exomanz** [comment]
[New release](https://github.com/Exomanz/BetterStaticLights/releases/tag/release-1.0.1) should fix this issue 👍
